// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/aberniando/xenshield/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetIPAddressStolenCardHistory mocks base method.
func (m *MockService) GetIPAddressStolenCardHistory(ctx context.Context, ipAddress string) (*entity.GetIPAddressStolenCardHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPAddressStolenCardHistory", ctx, ipAddress)
	ret0, _ := ret[0].(*entity.GetIPAddressStolenCardHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPAddressStolenCardHistory indicates an expected call of GetIPAddressStolenCardHistory.
func (mr *MockServiceMockRecorder) GetIPAddressStolenCardHistory(ctx, ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPAddressStolenCardHistory", reflect.TypeOf((*MockService)(nil).GetIPAddressStolenCardHistory), ctx, ipAddress)
}

// InsertTransaction mocks base method.
func (m *MockService) InsertTransaction(ctx context.Context, request *entity.InsertTransactionRequest) (*entity.InsertTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", ctx, request)
	ret0, _ := ret[0].(*entity.InsertTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockServiceMockRecorder) InsertTransaction(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockService)(nil).InsertTransaction), ctx, request)
}
